titre: "Neutre.CoMobi"
mail: "comobi@beta.gouv.fr"
tel: "04 00 00 00 00"
nom: "Version Neutre"
formulaire: "https://docs.google.com/forms/d/e/1FAIpQLSfirgGZ4B_OnP3oe9q_CxMi3Lm5hpCyk_GSIdm9wtizvq3RMA/viewform?usp=sf_link"

couleurs: 
  bouton_rechercher: "#199bb0"
  bouton_proposer: "#22aa75"
  odd_section_color: "#ecf0f1"

bandeau:
  image: "/assets/images/logo-comobi-long-web.png"
  texte: "Bandeau neutre"

## Les sections suivantes ne sont pas à modifier
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - direct/
  - outil-metier/