titre: "Neutre.CoMobi"
mail: "comobi@beta.gouv.fr"
tel: "04 00 00 00 00"
nom: "Version Neutre"
formulaire: "https://docs.google.com/forms/d/e/1FAIpQLSeInZJD79GJ-qg3Tkjz47uqsVgsZVy5awevxvhB67jK8KGGJQ/viewform?usp=sf_link"

couleurs: 
  bouton_rechercher: "#199bb0"
  bouton_proposer: "#22aa75"
  odd_section_color: "#ecf0f1"

bandeau:
  image: "/assets/images/logo-comobi-long-web.png"
  texte: "Bandeau neutre"

## Les sections suivantes ne sont pas à modifier
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - _scripts/

keep_files:
  - build